alias la="ls -lshAG"
alias gcom "git commit -a -m"
alias ga="git add ."
alias gs="git status"
alias gps="git push origin"
alias gpl="git pull origin"
alias gf="git fetch origin"
alias gm="git merge"
alias gb="git branch"
alias gst="git stash"
alias gd="git diff"
